version: "1"
rules:
  - base: master
    upstream: openwrt:master
    mergeMethod: hardreset
  - base: openwrt-18.06
    upstream: openwrt:openwrt-18.06
    mergeMethod: hardreset
  - base: openwrt-19.07
    upstream: openwrt:openwrt-19.07
    mergeMethod: hardreset
  - base: openwrt-21.02
    upstream: openwrt:openwrt-21.02
    mergeMethod: hardreset
  - base: openwrt-22.03
    upstream: openwrt:openwrt-22.03
    mergeMethod: hardreset
  - base: openwrt-23.05
    upstream: openwrt:openwrt-23.05
    mergeMethod: hardreset
